# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CSS Components
email: your-email@domain.com
description: "CSS Components são componentes criado somente usando css com todo seu poder sem nada de javascript ou jquery"
keywords: "components, css, pure css, css components, modal css, card css, carrousel css, menu mobile css"
twitterTitle: "CSS Components"
twitterDescription: "CSS Components são componentes criado somente usando css com todo seu poder sem nada de javascript ou jquery"
twitterUrl: "http://hjdesigner.github.io/css-components/"
twitterImage: "http://hjdesigner.github.io/css-components/images/css-components.jpg"
ogTitle: "CSS Components"
ogDescription: "CSS Components são componentes criado somente usando css com todo seu poder sem nada de javascript ou jquery"
ogImage: "http://hjdesigner.github.io/css-components/images/css-components.jpg"
ogUrl: "http://hjdesigner.github.io/css-components/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://henriquemelanda.com.br/css-components/" # the base hostname & protocol for your site
twitter: https://www.twitter.com/coisadedev
github:  https://www.github.com/hjdesigner
facebook: https://www.facebook.com/hjFrontEnd
codepen: https://codepen.io/hjdesigner/
linkedin: https://br.linkedin.com/in/coisadedev

sass:
  style: compressed

# Build settings
markdown: kramdown
